resilience4j.circuitbreaker:
  instances:
    productOfferingConsumerCommandKey:
      slidingWindowType: TIME_BASED
      failureRateThreshold: 50
      slidingWindowSize: 150
      minimumNumberOfCalls: 2
      slowCallDurationThreshold: 18000
      slowCallRateThreshold: 100
      waitDurationInOpenState: 70000ms
      permittedNumberOfCallsInHalfOpenState: 2
